### ISSUE TITLE
Banned me for no reason and now how to fetch bulk data?

### ISSUE THREAD

**Issue by quetzalsly** [erorus/newsstand#3]
I was trying to simply query about 700 items like this:

```
https://theunderminejournal.com/api/item.php?house=241&item=something
sleep(100)
```

I realise I put sleep too low, but there was no where on the tuj page that said anything about rate limits, and why am I perma banned now? usually API's just time you out so you can adjust your code and try again in a few min. Is it possible to be unbanned please?

It would be a lot easier if I could just query every single item in one go, is there such a thing?
Thanks

**Comment by erorus** [comment]
You were banned for sending automated requests to the site. We do not advertise a public API anywhere so you should not assume that automated requests are supported.

> no where on the tuj page that said anything about rate limits

People who use the website with a browser, like a human, typically don't hit the rate limits.

If you read the bottom of the contact page, you'll find resources you can use with automated data collection.
