### ISSUE TITLE
Missing Shadowlands Professions

### ISSUE THREAD

**Issue by anasypany** [erorus/newsstand#5]
Looks like TUJ hasn't been updated for shadowlands yet. Not sure if this is something already being worked on but it's definitely something desired by the wow economy community (as seen in [this reddit post](https://www.reddit.com/r/woweconomy/comments/k0zkcf/the_undermine_journal_custom_raw_mats_for/)).

**Comment by erorus** [comment]
I didn't see this until today, but that reddit post was a nice shortcut for me to find some item IDs, so thanks for that.
